server:
  port: 8769

spring:
  application:
    name: zipkin-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false