spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:8769
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka/
# routes to serviceId 这里边是通过serviceid来绑定地址，当在路径后添加/api-a/   则是访问service-A对应的服务。
zuul:
  routes:
    service1:
      path: /service1/**
      serviceId: service1
    service2:
      path: /service2/**
      serviceId: service2

# routes to url  这里是绑定具体的ip地址
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:2224/


