server:
  port: 2230

spring:
  application:
    name: auth
  zipkin:
    base-url: http://localhost:8769
  sleuth:
    sampler:
      percentage: 1.0

  redis:
    host: 127.0.0.1
    password: 5211314
    port: 6379
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka/
