server:
  port: 2225

spring:
  application:
    name: service2
  zipkin:
    base-url: http://localhost:8769
  sleuth:
    sampler:
      percentage: 1.0

  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver  #com.mysql.jdbc.Driver
    username: root
    password: 5211314
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka/

# 分布式事物
tm:
  manager:
    url: http://localhost:7000/tx/manager/

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.service2.entity  # 注意：对应实体类的路径