server:
  port: 2225

spring:
  application:
    name: service2
  zipkin:
    base-url: http://localhost:8769
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka/
